name: Build and Push to AWS ECR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'
        # The action automatically picks up AWS credentials from the environment.

      - name: Build Docker image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-repo  # Change to your repository name in ECR
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Building image $REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

      - name: Push Docker image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-repo
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "Pushing image $REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
